# cronからは常にproduction環境で起動します
# 基本的にはこちらのみ設定してください
production:
    # radikoで録音するチャンネルを設定してください
    # channel code (QRRなど) についてはREADME.mdのFAQを参照してください
    radiko_channels:
        - QRR # bunka housou
        - LFR # nippon housou

    # ファイルを保存(archive)するディレクトリを設定してください（フルパス）
    # このディレクトリ以下にサブディレクトリやファイルが作成されます
    # cronが実行されるユーザーにrwxのpermissionが与えられるようにしてください
    archive_dir: <%= Rails.root.join('public', 'system') %>

    # ダウンロード中などにファイルを一時的に置いておくディレクトリを設定してください（フルパス）
    # 一時的とはいえ、デフォルトで自己防止のためこのディレクトリのデータは30日ほど削除されません (lib/main/workaround.rbのrm_working_filesを参照)
    # そのためそれなりにおおきな容量となります
    # cronが実行されるユーザーにrwxのpermissionが与えられるようにしてください
    working_dir: <%= Rails.root.join('tmp', 'working') %>

    #ニコニコ おそらくプレミアム会員必須
    niconico:
        username: 'USERNAME'
        password: 'PASSWORD'
        live:
            # 録画(タイムシフトの取得)をしたい生放送をキーワードで指定
            keywords:
                - '村川梨衣'
                - '麻倉もも'

development:
    radiko_channels:
        - QRR # bunka housou
        - LFR # nippon housou
    archive_dir: /tmp/net-radio-archive
    working_dir: /tmp/net-radio-working
