# cronからは常にproduction環境で起動します
# 基本的にはこちらのみ設定してください
production:

    # ファイルを保存(archive)するディレクトリを設定してください（フルパス）
    # このディレクトリ以下にサブディレクトリやファイルが作成されます
    # cronが実行されるユーザーにrwxのpermissionが与えられるようにしてください
    archive_dir: <%= Rails.root.join('public', 'system') %>

    # ダウンロード中などにファイルを一時的に置いておくディレクトリを設定してください（フルパス）
    # 一時的とはいえ、デフォルトで事故防止のためこのディレクトリのデータは30日ほど削除されません (lib/main/workaround.rbのrm_working_filesを参照)
    # そのためそれなりにおおきな容量となります
    # cronが実行されるユーザーにrwxのpermissionが与えられるようにしてください
    working_dir: <%= Rails.root.join('tmp', 'working') %>

    working_dir_delete_days: 30

    # radikoで録音するチャンネルを設定してください
    # channel code (QRRなど) についてはREADME.mdのFAQを参照してください
    radiko_channels:
        - QRR # bunka housou
        - LFR # nippon housou

    # AG-ON (導入難易度高め。詳しくはREADME参照)
    # 録画しない場合はこの項目ごと消すと何もしません
    # これのみSelenium WebDriverを使っていたり、ffmpegでHLSを処理していたりと特殊なので
    # その辺が原因で動かない可能性もあります。エラーがでたらとりあえず項目消してみてください
    #agon:
    #    # AG-ONにアカウント登録してそのアカウントを設定してください
    #    mail: 'foo@example.com'
    #    password: 'XXXXXX'

    #    # Seleniumの実行にheadless gemとxvfbを使用するか
    #    # falseの場合はSeleniumでfirefoxが普通に起動するようにしておいてください
    #    #   (LinuxであればDISPLAY環境変数がセットされているように)
    #    #   Mac OS Xの場合は基本的にfalseにしてください
    #    # trueの場合はxvfbをインストールしておいてください (Ubuntu/Debianであれば `apt-get install xvfb`)
    #    headless: false
    # ニコニコ(開発中。恐ろしく不安定) おそらくプレミアム会員必須
    # 録画しない場合はこの項目ごと消すと何もしません
    #niconico:
    #    username: 'USERNAME'
    #    password: 'PASSWORD'
    #    live:
    #        # 録画(タイムシフトの取得)をしたい生放送をキーワードで指定
    #        keywords:
    #            - '村川梨衣'
    #            - '麻倉もも'

development:
    radiko_channels:
        - QRR # bunka housou
        - LFR # nippon housou
    archive_dir: /tmp/net-radio-archive
    working_dir: /tmp/net-radio-working
